"""
Data ingestion layer.

Provides a single `DataIngestor` façade that loads AIS (Global Fishing Watch
schema) and every static/environmental context layer (BMKG, bathymetry,
coastline, ports, National Shipping Lane, EEZ) regardless of whether the
underlying files are the licensed real datasets or the synthetic stand-ins
generated by `synthetic.py`. Downstream code (cleaning, feature engineering,
graph construction) only depends on the DataFrame schemas below, never on
file paths -- this is what makes "swap synthetic for real data" a one-file
change.

Expected real-data schemas
---------------------------
AIS (Global Fishing Watch, per-message):
    mmsi, timestamp, lat, lon, sog, cog, heading, nav_status,
    vessel_type, length, width, draft

Ports (Indonesian Ports):
    port_id, lat, lon, capacity_teu

National Shipping Lane (BIG):
    lane_id, segment_id, lat_start, lon_start, lat_end, lon_end

Coastline:
    lat, lon, seq

Bathymetry:
    lat, lon, depth_m

BMKG weather/wind/wave:
    station_lat, station_lon, timestamp, wind_speed_ms, wave_height_m,
    wave_direction_deg, weather_code

EEZ (optional):
    polygon geometry (WKT) with a single Indonesia EEZ boundary
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Dict, Optional

import pandas as pd

from ..config import Config


@dataclass
class MaritimeDataset:
    ais: pd.DataFrame
    ports: pd.DataFrame
    lanes: pd.DataFrame
    coastline: pd.DataFrame
    bathymetry: pd.DataFrame
    weather: pd.DataFrame
    protected_areas: pd.DataFrame
    eez_polygon_wkt: Optional[str] = None


class DataIngestor:
    """Loads every dataset layer required by the pipeline from a directory
    of parquet/csv files following the schemas documented in this module's
    docstring. Falls back to on-the-fly synthetic generation if the
    directory is empty, so the pipeline is always runnable.
    """

    def __init__(self, cfg: Config):
        self.cfg = cfg

    def _load_table(self, directory: str, name: str) -> Optional[pd.DataFrame]:
        for ext in (".parquet", ".csv"):
            path = os.path.join(directory, f"{name}{ext}")
            if os.path.exists(path):
                return pd.read_parquet(path) if ext == ".parquet" else pd.read_csv(path)
        return None

    def load(self, use_synthetic_if_missing: bool = True) -> MaritimeDataset:
        raw_dir = self.cfg.paths.abs(self.cfg.paths.raw_dir)
        synth_dir = self.cfg.paths.abs(self.cfg.paths.synthetic_dir)

        tables = {}
        for name in ("ais_raw", "ports", "shipping_lanes", "coastline",
                     "bathymetry", "bmkg_weather", "protected_areas"):
            tables[name] = self._load_table(raw_dir, name)

        missing = [k for k, v in tables.items() if v is None]
        if missing:
            if not use_synthetic_if_missing:
                raise FileNotFoundError(f"Missing real datasets: {missing}")
            for name in missing:
                fallback = self._load_table(synth_dir, name)
                if fallback is None:
                    from . import synthetic
                    synthetic.generate_all(self.cfg)
                    fallback = self._load_table(synth_dir, name)
                tables[name] = fallback

        return MaritimeDataset(
            ais=tables["ais_raw"],
            ports=tables["ports"],
            lanes=tables["shipping_lanes"],
            coastline=tables["coastline"],
            bathymetry=tables["bathymetry"],
            weather=tables["bmkg_weather"],
            protected_areas=tables["protected_areas"],
            eez_polygon_wkt=None,  # optional layer, not required by any hard dependency
        )
